spring.application.name=pos_system

server.port=5000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/posDB
spring.datasource.username=root
spring.datasource.password=yashraj@123
